// ═══════════════════════════════════════════════════════════════════════════════
//  s7Signals.js — NC/PLC interface signals for SINUMERIK 840D.
//
//  GENERATED, then hand-verified. Do not edit rows by hand casually — regenerate
//  from the manual (see scripts). Pure data. Imports nothing.
//
//  SOURCE (every row):
//    SINUMERIK 840D sl — List Manual "NC variables and interface signals",
//    05/2017, A5E40870419, chapter 5 "Interface signals - detailed description".
//    Transcribed programmatically from the manual's own signal index; names and
//    directions are the manual's, not inferred. Signal flow (NC↔PLC) is taken
//    from each signal's "Signal flow" line where the manual states one; where it
//    does not, dir is null rather than guessed.
//
//  CONTROLS: tagged 840D sl AND 840D powerline — the DB10/11/18/19/21/31 NC/PLC
//    interface is common to the 840D platform. 828D uses a different interface
//    map (DB1200/1600/...) and is intentionally not populated from this manual.
//
//  RANGE RULE: DB31-61 are per-axis, DB21-30 per-channel. A class stores a db
//    range + offset, so DB34 resolves to "Axis 4" without 31 copies per signal.
//
//  EXCLUDED: tool-management DB71-74 signals use relative (n+k) addressing rather
//    than a fixed DBX byte.bit, so they do not fit an address lookup and are not
//    included here.
// ═══════════════════════════════════════════════════════════════════════════════

export const CONTROLS = [
    { id: "840Dsl", label: "SINUMERIK 840D sl" },
    { id: "840Dpl", label: "SINUMERIK 840D powerline" },
    { id: "828D", label: "SINUMERIK 828D" },
];

const SL_PL = ["840Dsl", "840Dpl"];
const SOURCE = "840D sl Lists Manual (NC variables and interface signals), A5E40870419, ch.5";

// class key -> { label, db range, axis/channel offset }
const CLASS = {
    nck:  { label: "NCK",          db: [10, 10], offset: 0 },
    bag:  { label: "Mode group",   db: [11, 11], offset: 0 },
    spl:  { label: "Safety SPL",   db: [18, 18], offset: 0 },
    hmi:  { label: "HMI/MMC",      db: [19, 19], offset: 0 },
    chan: { label: "Channel",      db: [21, 30], offset: 20 },
    axis: { label: "Axis/spindle", db: [31, 61], offset: 30 },
};

// Compact rows: [id, class, type, byte, bit|null, dir|null, name]
const ROWS = [
  ["nck-0-0","nck","DBX",0,0,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-1","nck","DBX",0,1,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-2","nck","DBX",0,2,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-3","nck","DBX",0,3,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-4","nck","DBX",0,4,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-5","nck","DBX",0,5,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-6","nck","DBX",0,6,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-0-7","nck","DBX",0,7,"PLC->NC","digital NC inputs 1 - 8: Lock"],
  ["nck-1-0","nck","DBX",1,0,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-1","nck","DBX",1,1,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-2","nck","DBX",1,2,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-3","nck","DBX",1,3,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-4","nck","DBX",1,4,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-5","nck","DBX",1,5,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-6","nck","DBX",1,6,null,"digital NC inputs 1 - 8: Set"],
  ["nck-1-7","nck","DBX",1,7,null,"digital NC inputs 1 - 8: Set"],
  ["nck-4-0","nck","DBX",4,0,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-1","nck","DBX",4,1,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-2","nck","DBX",4,2,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-3","nck","DBX",4,3,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-4","nck","DBX",4,4,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-5","nck","DBX",4,5,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-6","nck","DBX",4,6,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-4-7","nck","DBX",4,7,null,"digital NC outputs 1 - 8: Lock"],
  ["nck-5-0","nck","DBX",5,0,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-1","nck","DBX",5,1,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-2","nck","DBX",5,2,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-3","nck","DBX",5,3,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-4","nck","DBX",5,4,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-5","nck","DBX",5,5,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-6","nck","DBX",5,6,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-5-7","nck","DBX",5,7,null,"digital NC outputs 1 - 8: Overwrite"],
  ["nck-6-0","nck","DBX",6,0,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-1","nck","DBX",6,1,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-2","nck","DBX",6,2,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-3","nck","DBX",6,3,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-4","nck","DBX",6,4,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-5","nck","DBX",6,5,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-6","nck","DBX",6,6,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-6-7","nck","DBX",6,7,null,"digital NC outputs 1 - 8: Setting value"],
  ["nck-7-0","nck","DBX",7,0,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-1","nck","DBX",7,1,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-2","nck","DBX",7,2,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-3","nck","DBX",7,3,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-4","nck","DBX",7,4,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-5","nck","DBX",7,5,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-6","nck","DBX",7,6,null,"digital NC outputs 1 - 8: Target"],
  ["nck-7-7","nck","DBX",7,7,null,"digital NC outputs 1 - 8: Target"],
  ["nck-56-1","nck","DBX",56,1,"PLC->NC","Emergency Stop"],
  ["nck-56-2","nck","DBX",56,2,"PLC->NC","acknowledge Emergency Stop"],
  ["nck-56-4","nck","DBX",56,4,"PLC->NC","key-operated switch position 0 - 3"],
  ["nck-56-5","nck","DBX",56,5,"PLC->NC","key-operated switch position 0 - 3"],
  ["nck-56-6","nck","DBX",56,6,"PLC->NC","key-operated switch position 0 - 3"],
  ["nck-56-7","nck","DBX",56,7,"PLC->NC","key-operated switch position 0 - 3"],
  ["nck-58-0","nck","DBX",58,0,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-1","nck","DBX",58,1,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-2","nck","DBX",58,2,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-3","nck","DBX",58,3,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-4","nck","DBX",58,4,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-5","nck","DBX",58,5,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-6","nck","DBX",58,6,null,"collision avoidance: Deactivate protection area group"],
  ["nck-58-7","nck","DBX",58,7,null,"collision avoidance: Deactivate protection area group"],
  ["nck-60-0","nck","DBX",60,0,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-1","nck","DBX",60,1,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-2","nck","DBX",60,2,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-3","nck","DBX",60,3,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-4","nck","DBX",60,4,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-5","nck","DBX",60,5,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-6","nck","DBX",60,6,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-60-7","nck","DBX",60,7,"NC->PLC","digital NC inputs 1 - 8: Actual value"],
  ["nck-64-0","nck","DBX",64,0,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-1","nck","DBX",64,1,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-2","nck","DBX",64,2,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-3","nck","DBX",64,3,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-4","nck","DBX",64,4,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-5","nck","DBX",64,5,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-6","nck","DBX",64,6,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-64-7","nck","DBX",64,7,"NC->PLC","digital NC outputs 1 - 8: Setpoint"],
  ["nck-97-0","nck","DBX",97,0,null,"channel number geometry axis handwheel 1"],
  ["nck-97-1","nck","DBX",97,1,null,"channel number geometry axis handwheel 1"],
  ["nck-97-2","nck","DBX",97,2,null,"channel number geometry axis handwheel 1"],
  ["nck-97-3","nck","DBX",97,3,null,"channel number geometry axis handwheel 1"],
  ["nck-98-0","nck","DBX",98,0,null,"channel number geometry axis handwheel 2"],
  ["nck-98-1","nck","DBX",98,1,null,"channel number geometry axis handwheel 2"],
  ["nck-98-2","nck","DBX",98,2,null,"channel number geometry axis handwheel 2"],
  ["nck-98-3","nck","DBX",98,3,null,"channel number geometry axis handwheel 2"],
  ["nck-99-0","nck","DBX",99,0,null,"channel number geometry axis handwheel 3"],
  ["nck-99-1","nck","DBX",99,1,null,"channel number geometry axis handwheel 3"],
  ["nck-99-2","nck","DBX",99,2,null,"channel number geometry axis handwheel 3"],
  ["nck-99-3","nck","DBX",99,3,null,"channel number geometry axis handwheel 3"],
  ["nck-100-0","nck","DBX",100,0,null,"axis number handwheel 1"],
  ["nck-100-1","nck","DBX",100,1,null,"axis number handwheel 1"],
  ["nck-100-2","nck","DBX",100,2,null,"axis number handwheel 1"],
  ["nck-100-3","nck","DBX",100,3,null,"axis number handwheel 1"],
  ["nck-100-4","nck","DBX",100,4,null,"axis number handwheel 1"],
  ["nck-100-5","nck","DBX",100,5,null,"define handwheel 1 as contour handwheel"],
  ["nck-100-6","nck","DBX",100,6,null,"handwheel 1 selected"],
  ["nck-100-7","nck","DBX",100,7,null,"machine axis handwheel 1"],
  ["nck-101-0","nck","DBX",101,0,null,"axis number handwheel 2"],
  ["nck-101-1","nck","DBX",101,1,null,"axis number handwheel 2"],
  ["nck-101-2","nck","DBX",101,2,null,"axis number handwheel 2"],
  ["nck-101-3","nck","DBX",101,3,null,"axis number handwheel 2"],
  ["nck-101-4","nck","DBX",101,4,null,"axis number handwheel 2"],
  ["nck-101-5","nck","DBX",101,5,null,"define handwheel 2 as contour handwheel"],
  ["nck-101-6","nck","DBX",101,6,null,"handwheel 2 selected"],
  ["nck-101-7","nck","DBX",101,7,null,"machine axis handwheel 2"],
  ["nck-102-0","nck","DBX",102,0,null,"axis number handwheel 3"],
  ["nck-102-1","nck","DBX",102,1,null,"axis number handwheel 3"],
  ["nck-102-2","nck","DBX",102,2,null,"axis number handwheel 3"],
  ["nck-102-3","nck","DBX",102,3,null,"axis number handwheel 3"],
  ["nck-102-4","nck","DBX",102,4,null,"axis number handwheel 3"],
  ["nck-102-5","nck","DBX",102,5,null,"define handwheel 3 as contour handwheel"],
  ["nck-102-6","nck","DBX",102,6,null,"handwheel 3 selected"],
  ["nck-102-7","nck","DBX",102,7,null,"machine axis handwheel 3"],
  ["nck-103-0","nck","DBX",103,0,null,"remote diagnosis active"],
  ["nck-103-5","nck","DBX",103,5,null,"AT box ready"],
  ["nck-103-6","nck","DBX",103,6,null,"HMI temperature limit"],
  ["nck-103-7","nck","DBX",103,7,null,"HMI battery alarm"],
  ["nck-104-7","nck","DBX",104,7,"NC->PLC","NC-CPU ready"],
  ["nck-106-1","nck","DBX",106,1,"NC->PLC","Emergency Stop active"],
  ["nck-107-0","nck","DBX",107,0,"NC->PLC","probe actuated"],
  ["nck-107-1","nck","DBX",107,1,"NC->PLC","probe actuated"],
  ["nck-107-6","nck","DBX",107,6,"NC->PLC","NCU link active"],
  ["nck-108-3","nck","DBX",108,3,"NC->PLC","SINUMERIK Operate at OPI ready"],
  ["nck-108-5","nck","DBX",108,5,"NC->PLC","drives in cyclic operation"],
  ["nck-108-6","nck","DBX",108,6,"NC->PLC","drive ready"],
  ["nck-108-7","nck","DBX",108,7,"NC->PLC","NC ready"],
  ["nck-109-0","nck","DBX",109,0,"NC->PLC","NC alarm active"],
  ["nck-109-5","nck","DBX",109,5,"NC->PLC","heat sink temperature alarm, NCU"],
  ["nck-109-6","nck","DBX",109,6,"NC->PLC","air temperature alarm"],
  ["nck-109-7","nck","DBX",109,7,"NC->PLC","NC battery alarm"],
  ["nck-110-0","nck","DBX",110,0,"NC->PLC","software cams: minus cam signal 1 to 32"],
  ["nck-114-0","nck","DBX",114,0,"NC->PLC","software cams: plus cam signal 1 to 32"],
  ["nck-122-0","nck","DBX",122,0,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-1","nck","DBX",122,1,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-2","nck","DBX",122,2,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-3","nck","DBX",122,3,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-4","nck","DBX",122,4,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-5","nck","DBX",122,5,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-6","nck","DBX",122,6,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-122-7","nck","DBX",122,7,"PLC->NC","digital NC inputs 9 - 16: Lock"],
  ["nck-123-0","nck","DBX",123,0,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-1","nck","DBX",123,1,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-2","nck","DBX",123,2,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-3","nck","DBX",123,3,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-4","nck","DBX",123,4,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-5","nck","DBX",123,5,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-6","nck","DBX",123,6,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-123-7","nck","DBX",123,7,"PLC->NC","digital NC inputs 9 - 16: Set"],
  ["nck-124-0","nck","DBX",124,0,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-1","nck","DBX",124,1,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-2","nck","DBX",124,2,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-3","nck","DBX",124,3,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-4","nck","DBX",124,4,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-5","nck","DBX",124,5,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-6","nck","DBX",124,6,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-124-7","nck","DBX",124,7,"PLC->NC","digital NC inputs 17 - 24: Lock"],
  ["nck-125-0","nck","DBX",125,0,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-1","nck","DBX",125,1,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-2","nck","DBX",125,2,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-3","nck","DBX",125,3,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-4","nck","DBX",125,4,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-5","nck","DBX",125,5,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-6","nck","DBX",125,6,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-125-7","nck","DBX",125,7,"PLC->NC","digital NC inputs 17 - 24: Set"],
  ["nck-126-0","nck","DBX",126,0,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-1","nck","DBX",126,1,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-2","nck","DBX",126,2,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-3","nck","DBX",126,3,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-4","nck","DBX",126,4,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-5","nck","DBX",126,5,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-6","nck","DBX",126,6,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-126-7","nck","DBX",126,7,"PLC->NC","digital NC inputs 25 - 32: Lock"],
  ["nck-127-0","nck","DBX",127,0,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-1","nck","DBX",127,1,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-2","nck","DBX",127,2,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-3","nck","DBX",127,3,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-4","nck","DBX",127,4,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-5","nck","DBX",127,5,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-6","nck","DBX",127,6,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-127-7","nck","DBX",127,7,"PLC->NC","digital NC inputs 25 - 32: Set"],
  ["nck-128-0","nck","DBX",128,0,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-1","nck","DBX",128,1,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-2","nck","DBX",128,2,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-3","nck","DBX",128,3,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-4","nck","DBX",128,4,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-5","nck","DBX",128,5,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-6","nck","DBX",128,6,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-128-7","nck","DBX",128,7,"PLC->NC","digital NC inputs 33 - 40: Lock"],
  ["nck-129-0","nck","DBX",129,0,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-1","nck","DBX",129,1,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-2","nck","DBX",129,2,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-3","nck","DBX",129,3,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-4","nck","DBX",129,4,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-5","nck","DBX",129,5,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-6","nck","DBX",129,6,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-129-7","nck","DBX",129,7,"PLC->NC","digital NC inputs 33 - 40: Set"],
  ["nck-130-0","nck","DBX",130,0,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-1","nck","DBX",130,1,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-2","nck","DBX",130,2,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-3","nck","DBX",130,3,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-4","nck","DBX",130,4,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-5","nck","DBX",130,5,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-6","nck","DBX",130,6,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-130-7","nck","DBX",130,7,"PLC->NC","digital NC outputs 9 - 16: Lock"],
  ["nck-131-0","nck","DBX",131,0,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-1","nck","DBX",131,1,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-2","nck","DBX",131,2,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-3","nck","DBX",131,3,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-4","nck","DBX",131,4,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-5","nck","DBX",131,5,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-6","nck","DBX",131,6,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-131-7","nck","DBX",131,7,"PLC->NC","digital NC outputs 9 - 16: Overwrite"],
  ["nck-132-0","nck","DBX",132,0,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-1","nck","DBX",132,1,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-2","nck","DBX",132,2,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-3","nck","DBX",132,3,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-4","nck","DBX",132,4,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-5","nck","DBX",132,5,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-6","nck","DBX",132,6,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-132-7","nck","DBX",132,7,"PLC->NC","digital NC outputs 9 - 16: Setting value"],
  ["nck-133-0","nck","DBX",133,0,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-1","nck","DBX",133,1,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-2","nck","DBX",133,2,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-3","nck","DBX",133,3,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-4","nck","DBX",133,4,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-5","nck","DBX",133,5,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-6","nck","DBX",133,6,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-133-7","nck","DBX",133,7,"PLC->NC","digital NC outputs 9 - 16: Target"],
  ["nck-134-0","nck","DBX",134,0,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-1","nck","DBX",134,1,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-2","nck","DBX",134,2,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-3","nck","DBX",134,3,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-4","nck","DBX",134,4,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-5","nck","DBX",134,5,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-6","nck","DBX",134,6,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-134-7","nck","DBX",134,7,"PLC->NC","digital NC outputs 17 - 24: Lock"],
  ["nck-135-0","nck","DBX",135,0,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-1","nck","DBX",135,1,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-2","nck","DBX",135,2,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-3","nck","DBX",135,3,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-4","nck","DBX",135,4,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-5","nck","DBX",135,5,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-6","nck","DBX",135,6,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-135-7","nck","DBX",135,7,"PLC->NC","digital NC outputs 17 - 24: Overwrite"],
  ["nck-136-0","nck","DBX",136,0,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-1","nck","DBX",136,1,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-2","nck","DBX",136,2,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-3","nck","DBX",136,3,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-4","nck","DBX",136,4,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-5","nck","DBX",136,5,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-6","nck","DBX",136,6,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-136-7","nck","DBX",136,7,"PLC->NC","digital NC outputs 17 - 24: Setting value"],
  ["nck-137-0","nck","DBX",137,0,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-1","nck","DBX",137,1,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-2","nck","DBX",137,2,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-3","nck","DBX",137,3,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-4","nck","DBX",137,4,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-5","nck","DBX",137,5,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-6","nck","DBX",137,6,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-137-7","nck","DBX",137,7,"PLC->NC","digital NC outputs 17 - 24: Target"],
  ["nck-138-0","nck","DBX",138,0,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-1","nck","DBX",138,1,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-2","nck","DBX",138,2,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-3","nck","DBX",138,3,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-4","nck","DBX",138,4,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-5","nck","DBX",138,5,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-6","nck","DBX",138,6,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-138-7","nck","DBX",138,7,"PLC->NC","digital NC outputs 25 - 32: Lock"],
  ["nck-139-0","nck","DBX",139,0,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-1","nck","DBX",139,1,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-2","nck","DBX",139,2,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-3","nck","DBX",139,3,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-4","nck","DBX",139,4,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-5","nck","DBX",139,5,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-6","nck","DBX",139,6,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-139-7","nck","DBX",139,7,"PLC->NC","digital NC outputs 25 - 32: Overwrite"],
  ["nck-140-0","nck","DBX",140,0,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-1","nck","DBX",140,1,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-2","nck","DBX",140,2,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-3","nck","DBX",140,3,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-4","nck","DBX",140,4,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-5","nck","DBX",140,5,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-6","nck","DBX",140,6,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-140-7","nck","DBX",140,7,"PLC->NC","digital NC outputs 25 - 32: Setting value"],
  ["nck-141-0","nck","DBX",141,0,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-1","nck","DBX",141,1,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-2","nck","DBX",141,2,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-3","nck","DBX",141,3,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-4","nck","DBX",141,4,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-5","nck","DBX",141,5,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-6","nck","DBX",141,6,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-141-7","nck","DBX",141,7,"PLC->NC","digital NC outputs 25 - 32: Target"],
  ["nck-142-0","nck","DBX",142,0,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-1","nck","DBX",142,1,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-2","nck","DBX",142,2,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-3","nck","DBX",142,3,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-4","nck","DBX",142,4,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-5","nck","DBX",142,5,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-6","nck","DBX",142,6,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-142-7","nck","DBX",142,7,"PLC->NC","digital NC outputs 33 - 40: Lock"],
  ["nck-143-0","nck","DBX",143,0,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-1","nck","DBX",143,1,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-2","nck","DBX",143,2,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-3","nck","DBX",143,3,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-4","nck","DBX",143,4,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-5","nck","DBX",143,5,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-6","nck","DBX",143,6,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-143-7","nck","DBX",143,7,"PLC->NC","digital NC outputs 33 - 40: Overwrite"],
  ["nck-144-0","nck","DBX",144,0,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-1","nck","DBX",144,1,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-2","nck","DBX",144,2,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-3","nck","DBX",144,3,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-4","nck","DBX",144,4,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-5","nck","DBX",144,5,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-6","nck","DBX",144,6,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-144-7","nck","DBX",144,7,"PLC->NC","digital NC outputs 33 - 40: Setting value"],
  ["nck-145-0","nck","DBX",145,0,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-1","nck","DBX",145,1,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-2","nck","DBX",145,2,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-3","nck","DBX",145,3,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-4","nck","DBX",145,4,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-5","nck","DBX",145,5,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-6","nck","DBX",145,6,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-145-7","nck","DBX",145,7,"PLC->NC","digital NC outputs 33 - 40: Target"],
  ["nck-146-0","nck","DBX",146,0,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-1","nck","DBX",146,1,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-2","nck","DBX",146,2,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-3","nck","DBX",146,3,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-4","nck","DBX",146,4,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-5","nck","DBX",146,5,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-6","nck","DBX",146,6,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-146-7","nck","DBX",146,7,"PLC->NC","analog NC inputs 1 - 8: Lock"],
  ["nck-147-0","nck","DBX",147,0,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-1","nck","DBX",147,1,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-2","nck","DBX",147,2,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-3","nck","DBX",147,3,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-4","nck","DBX",147,4,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-5","nck","DBX",147,5,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-6","nck","DBX",147,6,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-147-7","nck","DBX",147,7,"PLC->NC","analog NC inputs 1 - 8: Target"],
  ["nck-148-b","nck","DBW",148,null,"PLC->NC","analog NC outputs 1 - 8: Setting value"],
  ["nck-166-0","nck","DBX",166,0,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-1","nck","DBX",166,1,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-2","nck","DBX",166,2,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-3","nck","DBX",166,3,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-4","nck","DBX",166,4,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-5","nck","DBX",166,5,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-6","nck","DBX",166,6,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-166-7","nck","DBX",166,7,"PLC->NC","analog NC outputs 1 - 8: Overwrite"],
  ["nck-167-0","nck","DBX",167,0,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-1","nck","DBX",167,1,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-2","nck","DBX",167,2,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-3","nck","DBX",167,3,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-4","nck","DBX",167,4,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-5","nck","DBX",167,5,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-6","nck","DBX",167,6,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-167-7","nck","DBX",167,7,"PLC->NC","analog NC outputs 1 - 8: Target"],
  ["nck-168-0","nck","DBX",168,0,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-1","nck","DBX",168,1,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-2","nck","DBX",168,2,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-3","nck","DBX",168,3,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-4","nck","DBX",168,4,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-5","nck","DBX",168,5,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-6","nck","DBX",168,6,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-168-7","nck","DBX",168,7,"PLC->NC","analog NC outputs 1 - 8: Lock"],
  ["nck-170-b","nck","DBW",170,null,"PLC->NC","analog NC outputs 1 - 8: Setting value"],
  ["nck-186-0","nck","DBX",186,0,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-1","nck","DBX",186,1,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-2","nck","DBX",186,2,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-3","nck","DBX",186,3,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-4","nck","DBX",186,4,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-5","nck","DBX",186,5,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-6","nck","DBX",186,6,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-186-7","nck","DBX",186,7,"NC->PLC","digital NC inputs 9 - 16: Actual value"],
  ["nck-187-0","nck","DBX",187,0,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-1","nck","DBX",187,1,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-2","nck","DBX",187,2,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-3","nck","DBX",187,3,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-4","nck","DBX",187,4,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-5","nck","DBX",187,5,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-6","nck","DBX",187,6,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-187-7","nck","DBX",187,7,"NC->PLC","digital NC inputs 17 - 24: Actual value"],
  ["nck-188-0","nck","DBX",188,0,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-1","nck","DBX",188,1,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-2","nck","DBX",188,2,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-3","nck","DBX",188,3,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-4","nck","DBX",188,4,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-5","nck","DBX",188,5,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-6","nck","DBX",188,6,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-188-7","nck","DBX",188,7,"NC->PLC","digital NC inputs 25 - 32: Actual value"],
  ["nck-189-0","nck","DBX",189,0,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-1","nck","DBX",189,1,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-2","nck","DBX",189,2,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-3","nck","DBX",189,3,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-4","nck","DBX",189,4,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-5","nck","DBX",189,5,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-6","nck","DBX",189,6,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-189-7","nck","DBX",189,7,"NC->PLC","digital NC inputs 33 - 40: Actual value"],
  ["nck-190-0","nck","DBX",190,0,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-1","nck","DBX",190,1,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-2","nck","DBX",190,2,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-3","nck","DBX",190,3,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-4","nck","DBX",190,4,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-5","nck","DBX",190,5,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-6","nck","DBX",190,6,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-190-7","nck","DBX",190,7,"NC->PLC","digital NC outputs 9 - 16: Setpoint"],
  ["nck-191-0","nck","DBX",191,0,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-1","nck","DBX",191,1,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-2","nck","DBX",191,2,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-3","nck","DBX",191,3,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-4","nck","DBX",191,4,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-5","nck","DBX",191,5,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-6","nck","DBX",191,6,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-191-7","nck","DBX",191,7,"NC->PLC","digital NC outputs 17 - 24: Setpoint"],
  ["nck-192-0","nck","DBX",192,0,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-1","nck","DBX",192,1,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-2","nck","DBX",192,2,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-3","nck","DBX",192,3,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-4","nck","DBX",192,4,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-5","nck","DBX",192,5,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-6","nck","DBX",192,6,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-192-7","nck","DBX",192,7,"NC->PLC","digital NC outputs 25 - 32: Setpoint"],
  ["nck-193-0","nck","DBX",193,0,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-1","nck","DBX",193,1,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-2","nck","DBX",193,2,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-3","nck","DBX",193,3,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-4","nck","DBX",193,4,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-5","nck","DBX",193,5,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-6","nck","DBX",193,6,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-193-7","nck","DBX",193,7,"NC->PLC","digital NC outputs 33 - 40: Setpoint"],
  ["nck-194-b","nck","DBW",194,null,"NC->PLC","analog NC inputs 1 - 8: Actual value"],
  ["nck-210-b","nck","DBW",210,null,"NC->PLC","analog NC outputs 1 - 8: Setpoint"],
  ["nck-226-0","nck","DBX",226,0,"NC->PLC","collision avoidance: Protection area active"],
  ["nck-234-0","nck","DBX",234,0,"PLC->NC","collision avoidance: Activate protection area"],
  ["nck-245-0","nck","DBX",245,0,"NC->PLC","Ethernet handwheel stationary"],
  ["nck-245-1","nck","DBX",245,1,"NC->PLC","Ethernet handwheel stationary"],
  ["nck-245-2","nck","DBX",245,2,"NC->PLC","Ethernet handwheel stationary"],
  ["nck-245-3","nck","DBX",245,3,"NC->PLC","Ethernet handwheel stationary"],
  ["nck-245-4","nck","DBX",245,4,"NC->PLC","Ethernet handwheel stationary"],
  ["nck-245-5","nck","DBX",245,5,"NC->PLC","Ethernet handwheel stationary"],
  ["bag-0-0","bag","DBX",0,0,"PLC->NC","AUTOMATIC mode"],
  ["bag-0-1","bag","DBX",0,1,"PLC->NC","MDI mode"],
  ["bag-0-2","bag","DBX",0,2,"PLC->NC","JOG mode"],
  ["bag-0-4","bag","DBX",0,4,"PLC->NC","mode change inhibit"],
  ["bag-0-5","bag","DBX",0,5,"PLC->NC","mode group stop"],
  ["bag-0-6","bag","DBX",0,6,"PLC->NC","mode group stop, axes plus spindles"],
  ["bag-0-7","bag","DBX",0,7,"PLC->NC","mode group reset"],
  ["bag-1-0","bag","DBX",1,0,"PLC->NC","TEACH IN machine function"],
  ["bag-1-1","bag","DBX",1,1,"PLC->NC","REPOS machine function"],
  ["bag-1-2","bag","DBX",1,2,"PLC->NC","REF machine function"],
  ["bag-1-6","bag","DBX",1,6,"PLC->NC","single block, type B"],
  ["bag-1-7","bag","DBX",1,7,"PLC->NC","single block, type A"],
  ["bag-4-0","bag","DBX",4,0,null,"AUTOMATIC mode selected"],
  ["bag-4-1","bag","DBX",4,1,null,"MDI mode selected"],
  ["bag-4-2","bag","DBX",4,2,null,"JOG mode selected"],
  ["bag-5-0","bag","DBX",5,0,null,"TEACH IN machine function selected"],
  ["bag-5-1","bag","DBX",5,1,null,"REPOS machine function selected"],
  ["bag-5-2","bag","DBX",5,2,null,"REF machine function selected"],
  ["bag-6-0","bag","DBX",6,0,"NC->PLC","AUTOMATIC mode active"],
  ["bag-6-1","bag","DBX",6,1,"NC->PLC","active MDI mode"],
  ["bag-6-2","bag","DBX",6,2,"NC->PLC","JOG mode active"],
  ["bag-6-3","bag","DBX",6,3,"NC->PLC","mode group ready"],
  ["bag-6-7","bag","DBX",6,7,"NC->PLC","all channels in the \"Reset\" state"],
  ["bag-7-0","bag","DBX",7,0,"NC->PLC","TEACH IN machine function active"],
  ["bag-7-1","bag","DBX",7,1,"NC->PLC","REPOS machine function active"],
  ["bag-7-2","bag","DBX",7,2,"NC->PLC","REF machine function active"],
  ["spl-36-0","spl","DBB",36,0,null,"SPL_READY"],
  ["spl-36-1","spl","DBB",36,1,null,"STOP_E"],
  ["spl-38-b","spl","DBB",38,null,null,"SPL inputs, SPL_DATA.INSEP[1"],
  ["spl-42-0","spl","DBB",42,0,"PLC->NC","SPL inputs, SPL_DATA.INSEP[33"],
  ["hmi-0-0","hmi","DBX",0,0,null,"brighten screen"],
  ["hmi-0-1","hmi","DBX",0,1,null,"darken screen"],
  ["hmi-0-2","hmi","DBX",0,2,null,"key lock"],
  ["hmi-0-3","hmi","DBX",0,3,null,"delete cancel alarms"],
  ["hmi-0-4","hmi","DBX",0,4,null,"delete recall alarms"],
  ["hmi-0-7","hmi","DBX",0,7,null,"actual values in the WCS"],
  ["hmi-6-b","hmi","DBB",6,null,null,"analog spindle 1, utilization as a percentage"],
  ["hmi-7-b","hmi","DBB",7,null,null,"analog spindle 2, utilization as a percentage"],
  ["hmi-8-b","hmi","DBB",8,null,null,"channel number"],
  ["hmi-10-b","hmi","DBB",10,null,null,"PLC hardkeys"],
  ["hmi-13-5","hmi","DBX",13,5,null,"NC program: unload"],
  ["hmi-13-6","hmi","DBX",13,6,null,"NC program: load"],
  ["hmi-13-7","hmi","DBX",13,7,null,"NC program: selection"],
  ["hmi-14-0","hmi","DBX",14,0,null,"PLC index"],
  ["hmi-14-1","hmi","DBX",14,1,null,"PLC index"],
  ["hmi-14-2","hmi","DBX",14,2,null,"PLC index"],
  ["hmi-14-3","hmi","DBX",14,3,null,"PLC index"],
  ["hmi-14-4","hmi","DBX",14,4,null,"PLC index"],
  ["hmi-14-5","hmi","DBX",14,5,null,"PLC index"],
  ["hmi-14-6","hmi","DBX",14,6,null,"PLC index"],
  ["hmi-14-7","hmi","DBX",14,7,null,"selects the file system"],
  ["hmi-15-b","hmi","DBB",15,null,null,"PLC line offset"],
  ["hmi-16-0","hmi","DBX",16,0,null,"PLC index: user control file"],
  ["hmi-16-1","hmi","DBX",16,1,null,"PLC index: user control file"],
  ["hmi-16-2","hmi","DBX",16,2,null,"PLC index: user control file"],
  ["hmi-16-3","hmi","DBX",16,3,null,"PLC index: user control file"],
  ["hmi-16-4","hmi","DBX",16,4,null,"PLC index: user control file"],
  ["hmi-16-5","hmi","DBX",16,5,null,"PLC index: user control file"],
  ["hmi-16-6","hmi","DBX",16,6,null,"PLC index: user control file"],
  ["hmi-16-7","hmi","DBX",16,7,null,"select file system"],
  ["hmi-17-b","hmi","DBB",17,null,null,"PLC line offset"],
  ["hmi-20-1","hmi","DBX",20,1,null,"screen is dark"],
  ["hmi-20-3","hmi","DBX",20,3,null,"cancel alarms deleted"],
  ["hmi-20-4","hmi","DBX",20,4,null,"recall alarms deleted"],
  ["hmi-20-6","hmi","DBX",20,6,null,"simulation active"],
  ["hmi-20-7","hmi","DBX",20,7,null,"switch MCS/WCS"],
  ["hmi-22-b","hmi","DBB",22,null,null,"actual channel number"],
  ["hmi-24-b","hmi","DBB",24,null,null,"actual screen number"],
  ["hmi-26-1","hmi","DBX",26,1,null,"job completed"],
  ["hmi-26-2","hmi","DBX",26,2,null,"error"],
  ["hmi-26-3","hmi","DBX",26,3,null,"active"],
  ["hmi-26-5","hmi","DBX",26,5,null,"unload"],
  ["hmi-26-6","hmi","DBX",26,6,null,"load"],
  ["hmi-26-7","hmi","DBX",26,7,null,"selection"],
  ["hmi-27-b","hmi","DBB",27,null,null,"error identification"],
  ["hmi-32-0","hmi","DBX",32,0,null,"function number"],
  ["hmi-32-1","hmi","DBX",32,1,null,"function number"],
  ["hmi-32-2","hmi","DBX",32,2,null,"function number"],
  ["hmi-32-3","hmi","DBX",32,3,null,"function number"],
  ["hmi-32-4","hmi","DBX",32,4,null,"function number"],
  ["hmi-32-5","hmi","DBX",32,5,null,"function number"],
  ["hmi-32-6","hmi","DBX",32,6,null,"function request"],
  ["hmi-32-7","hmi","DBX",32,7,null,"status"],
  ["hmi-33-b","hmi","DBB",33,null,null,"parameter 1 - 3"],
  ["hmi-36-b","hmi","DBB",36,null,null,"error identification"],
  ["chan-0-1","chan","DBX",0,1,"PLC->NC","RESU: backward/forward"],
  ["chan-0-2","chan","DBX",0,2,"PLC->NC","RESU: start retrace support"],
  ["chan-0-3","chan","DBX",0,3,"PLC->NC","activateDifferential Resolver Function"],
  ["chan-0-4","chan","DBX",0,4,"PLC->NC","activate single block"],
  ["chan-0-5","chan","DBX",0,5,"PLC->NC","activate M01"],
  ["chan-0-6","chan","DBX",0,6,"PLC->NC","activate dry run feedrate"],
  ["chan-1-0","chan","DBX",1,0,"PLC->NC","activate referencing"],
  ["chan-1-3","chan","DBX",1,3,"PLC->NC","time monitoring active"],
  ["chan-1-4","chan","DBX",1,4,"PLC->NC","clearance control (CLC): stop"],
  ["chan-1-5","chan","DBX",1,5,"PLC->NC","clearance control (CLC): Override"],
  ["chan-1-6","chan","DBX",1,6,"PLC->NC","PLC action completed"],
  ["chan-1-7","chan","DBX",1,7,"PLC->NC","activate program test"],
  ["chan-2-b","chan","DBB",2,null,"PLC->NC","activate \"skip block\""],
  ["chan-3-0","chan","DBX",3,0,"PLC->NC","stroke enable"],
  ["chan-3-1","chan","DBX",3,1,"PLC->NC","punch interface 1: Manual stroke initiation"],
  ["chan-3-2","chan","DBX",3,2,"PLC->NC","stroke suppression"],
  ["chan-3-3","chan","DBX",3,3,"PLC->NC","delayed stroke"],
  ["chan-3-4","chan","DBX",3,4,"PLC->NC","stroke inoperative"],
  ["chan-3-5","chan","DBX",3,5,"PLC->NC","punch interface 2: Manual stroke initiation"],
  ["chan-4-b","chan","DBB",4,null,"PLC->NC","feed rate override"],
  ["chan-5-b","chan","DBB",5,null,"PLC->NC","rapid traverse override"],
  ["chan-6-0","chan","DBX",6,0,"PLC->NC","feedrate disable"],
  ["chan-6-1","chan","DBX",6,1,"PLC->NC","read-in disable"],
  ["chan-6-2","chan","DBX",6,2,"PLC->NC","delete distance-to-go, channel-specific"],
  ["chan-6-4","chan","DBX",6,4,"PLC->NC","program level abort"],
  ["chan-6-6","chan","DBX",6,6,"PLC->NC","rapid traverse override active"],
  ["chan-6-7","chan","DBX",6,7,"PLC->NC","feed override active"],
  ["chan-7-0","chan","DBX",7,0,"PLC->NC","NC start disable"],
  ["chan-7-1","chan","DBX",7,1,"PLC->NC","NC Start"],
  ["chan-7-2","chan","DBX",7,2,"PLC->NC","NC Stop at the block limit"],
  ["chan-7-3","chan","DBX",7,3,"PLC->NC","NC Stop"],
  ["chan-7-4","chan","DBX",7,4,"PLC->NC","NC Stop axes plus spindles"],
  ["chan-7-7","chan","DBX",7,7,"PLC->NC","reset"],
  ["chan-8-0","chan","DBX",8,0,"PLC->NC","activate machine-related protection zone 1 - 10"],
  ["chan-10-0","chan","DBX",10,0,"PLC->NC","activate channel-specific protection zone 1 - 10"],
  ["chan-12-0","chan","DBX",12,0,"PLC->NC","geometry axis 1: activate handwheel"],
  ["chan-12-1","chan","DBX",12,1,"PLC->NC","geometry axis 1: activate handwheel"],
  ["chan-12-2","chan","DBX",12,2,"PLC->NC","geometry axis 1: activate handwheel"],
  ["chan-12-3","chan","DBX",12,3,"PLC->NC","feedrate stop, geometry axes 1 / 2 / 3"],
  ["chan-12-4","chan","DBX",12,4,"PLC->NC","geometry axis 1: traversing key lock"],
  ["chan-12-5","chan","DBX",12,5,"PLC->NC","geometry axis 1: rapid traverse override"],
  ["chan-12-6","chan","DBX",12,6,"PLC->NC","geometry axis 1: traversing keys \"Plus\" / \"Minus\""],
  ["chan-12-7","chan","DBX",12,7,"PLC->NC","geometry axis 1: traversing keys \"Plus\" / \"Minus\""],
  ["chan-13-0","chan","DBX",13,0,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-13-1","chan","DBX",13,1,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-13-2","chan","DBX",13,2,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-13-3","chan","DBX",13,3,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-13-4","chan","DBX",13,4,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-13-5","chan","DBX",13,5,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-13-6","chan","DBX",13,6,"PLC->NC","geometry axis 1: machine function request"],
  ["chan-15-0","chan","DBX",15,0,"PLC->NC","geometry axis 1: invert handwheel direction of rotation"],
  ["chan-16-0","chan","DBX",16,0,null,"geometry axis 2: activate handwheel"],
  ["chan-16-1","chan","DBX",16,1,null,"geometry axis 2: activate handwheel"],
  ["chan-16-2","chan","DBX",16,2,null,"geometry axis 2: activate handwheel"],
  ["chan-16-4","chan","DBX",16,4,null,"geometry axis 2: traversing key lock"],
  ["chan-16-5","chan","DBX",16,5,null,"geometry axis 2: rapid traverse override"],
  ["chan-16-6","chan","DBX",16,6,null,"geometry axis 2: traversing keys \"Plus\" / \"Minus\""],
  ["chan-16-7","chan","DBX",16,7,null,"geometry axis 2: traversing keys \"Plus\" / \"Minus\""],
  ["chan-17-0","chan","DBX",17,0,null,"geometry axis 2: machine function request"],
  ["chan-17-1","chan","DBX",17,1,null,"geometry axis 2: machine function request"],
  ["chan-17-2","chan","DBX",17,2,null,"geometry axis 2: machine function request"],
  ["chan-17-3","chan","DBX",17,3,null,"geometry axis 2: machine function request"],
  ["chan-17-4","chan","DBX",17,4,null,"geometry axis 2: machine function request"],
  ["chan-17-5","chan","DBX",17,5,null,"geometry axis 2: machine function request"],
  ["chan-17-6","chan","DBX",17,6,null,"geometry axis 2: machine function request"],
  ["chan-19-0","chan","DBX",19,0,null,"geometry axis 2: invert handwheel direction of rotation"],
  ["chan-20-0","chan","DBX",20,0,null,"geometry axis 3: activate handwheel"],
  ["chan-20-1","chan","DBX",20,1,null,"geometry axis 3: activate handwheel"],
  ["chan-20-2","chan","DBX",20,2,null,"geometry axis 3: activate handwheel"],
  ["chan-20-4","chan","DBX",20,4,null,"geometry axis 3: traversing key lock"],
  ["chan-20-5","chan","DBX",20,5,null,"geometry axis 3: rapid traverse override"],
  ["chan-20-6","chan","DBX",20,6,null,"geometry axis 3: traversing keys \"Plus\" / \"Minus\""],
  ["chan-20-7","chan","DBX",20,7,null,"geometry axis 3: traversing keys \"Plus\" / \"Minus\""],
  ["chan-21-0","chan","DBX",21,0,null,"geometry axis 3: machine function request"],
  ["chan-21-1","chan","DBX",21,1,null,"geometry axis 3: machine function request"],
  ["chan-21-2","chan","DBX",21,2,null,"geometry axis 3: machine function request"],
  ["chan-21-3","chan","DBX",21,3,null,"geometry axis 3: machine function request"],
  ["chan-21-4","chan","DBX",21,4,null,"geometry axis 3: machine function request"],
  ["chan-21-5","chan","DBX",21,5,null,"geometry axis 3: machine function request"],
  ["chan-21-6","chan","DBX",21,6,null,"geometry axis 3: machine function request"],
  ["chan-23-0","chan","DBX",23,0,null,"geometry axis 3: invert handwheel direction of rotation"],
  ["chan-24-3","chan","DBX",24,3,null,"Differential Resolver Functionselected"],
  ["chan-24-4","chan","DBX",24,4,"PLC->NC","select NC-associated M01"],
  ["chan-24-5","chan","DBX",24,5,null,"M01 selected"],
  ["chan-24-6","chan","DBX",24,6,null,"dry run feedrate selected"],
  ["chan-25-3","chan","DBX",25,3,null,"feedrate override selected for rapid traverse"],
  ["chan-29-0","chan","DBX",29,0,null,"activate fixed feedrate 1 - 4, path/geometry axes"],
  ["chan-29-1","chan","DBX",29,1,null,"activate fixed feedrate 1 - 4, path/geometry axes"],
  ["chan-29-2","chan","DBX",29,2,null,"activate fixed feedrate 1 - 4, path/geometry axes"],
  ["chan-29-3","chan","DBX",29,3,null,"activate fixed feedrate 1 - 4, path/geometry axes"],
  ["chan-29-4","chan","DBX",29,4,"PLC->NC","activate PTP travel"],
  ["chan-29-5","chan","DBX",29,5,"PLC->NC","tool manager: Deactivate workpiece counter"],
  ["chan-29-6","chan","DBX",29,6,"PLC->NC","tool manager: Deactivating wear monitoring"],
  ["chan-29-7","chan","DBX",29,7,"PLC->NC","tool manager: Tool lock not active"],
  ["chan-30-0","chan","DBX",30,0,null,"activate contour handwheel"],
  ["chan-30-1","chan","DBX",30,1,null,"activate contour handwheel"],
  ["chan-30-2","chan","DBX",30,2,null,"activate contour handwheel"],
  ["chan-30-3","chan","DBX",30,3,"PLC->NC","simulation contour handwheel: Activate"],
  ["chan-30-4","chan","DBX",30,4,"PLC->NC","simulation contour handwheel: Negative direction"],
  ["chan-30-5","chan","DBX",30,5,"PLC->NC","activate M0 / M1 associated with NC"],
  ["chan-30-6","chan","DBX",30,6,"PLC->NC","JOG circular travel"],
  ["chan-31-0","chan","DBX",31,0,"PLC->NC","REPOS mode"],
  ["chan-31-1","chan","DBX",31,1,"PLC->NC","REPOS mode"],
  ["chan-31-2","chan","DBX",31,2,"PLC->NC","REPOS mode"],
  ["chan-31-4","chan","DBX",31,4,"PLC->NC","REPOS activation"],
  ["chan-31-5","chan","DBX",31,5,"PLC->NC","contour handwheel: invert handwheel direction of rotation"],
  ["chan-32-1","chan","DBX",32,1,"NC->PLC","RESU: retrace mode active"],
  ["chan-32-2","chan","DBX",32,2,"NC->PLC","retrace support active"],
  ["chan-32-3","chan","DBX",32,3,"NC->PLC","action block active"],
  ["chan-32-4","chan","DBX",32,4,"NC->PLC","approach block active"],
  ["chan-32-5","chan","DBX",32,5,"NC->PLC","M00/M01 active"],
  ["chan-32-6","chan","DBX",32,6,"NC->PLC","last action block active"],
  ["chan-33-0","chan","DBX",33,0,"NC->PLC","referencing active"],
  ["chan-33-2","chan","DBX",33,2,null,"revolutional feedrate active"],
  ["chan-33-3","chan","DBX",33,3,"NC->PLC","handwheel override active"],
  ["chan-33-4","chan","DBX",33,4,"NC->PLC","block search active"],
  ["chan-33-5","chan","DBX",33,5,"NC->PLC","M02 / M30 active"],
  ["chan-33-6","chan","DBX",33,6,"NC->PLC","transformation active"],
  ["chan-33-7","chan","DBX",33,7,"NC->PLC","program test active"],
  ["chan-35-0","chan","DBX",35,0,"NC->PLC","program state \"running\""],
  ["chan-35-1","chan","DBX",35,1,"NC->PLC","program state \"wait\""],
  ["chan-35-2","chan","DBX",35,2,"NC->PLC","program state \"stopped\""],
  ["chan-35-3","chan","DBX",35,3,"NC->PLC","program state \"interrupted\""],
  ["chan-35-4","chan","DBX",35,4,"NC->PLC","program state \"aborted\""],
  ["chan-35-5","chan","DBX",35,5,"NC->PLC","channel state \"active\""],
  ["chan-35-6","chan","DBX",35,6,"NC->PLC","channel state \"interrupted\""],
  ["chan-35-7","chan","DBX",35,7,"NC->PLC","channel state \"reset\""],
  ["chan-36-2","chan","DBX",36,2,"NC->PLC","all axes that have to be referenced have been referenced"],
  ["chan-36-3","chan","DBX",36,3,"NC->PLC","all axes stationary"],
  ["chan-36-4","chan","DBX",36,4,"NC->PLC","interrupt handling active"],
  ["chan-36-5","chan","DBX",36,5,"NC->PLC","channel ready"],
  ["chan-36-6","chan","DBX",36,6,"NC->PLC","channel-specific NC alarm active"],
  ["chan-36-7","chan","DBX",36,7,"NC->PLC","NC alarm with machining stop active"],
  ["chan-37-0","chan","DBX",37,0,"PLC->NC","contour handwheel active"],
  ["chan-37-1","chan","DBX",37,1,"PLC->NC","contour handwheel active"],
  ["chan-37-2","chan","DBX",37,2,"PLC->NC","contour handwheel active"],
  ["chan-37-3","chan","DBX",37,3,"NC->PLC","clearance control (CLC): Active"],
  ["chan-37-4","chan","DBX",37,4,"NC->PLC","clearance control (CLC): Stop at the lower motion limit"],
  ["chan-37-5","chan","DBX",37,5,"NC->PLC","clearance control (CLC): Stop at the upper motion limit"],
  ["chan-37-6","chan","DBX",37,6,"NC->PLC","read-in disable is ignored"],
  ["chan-37-7","chan","DBX",37,7,"NC->PLC","stop at block end is ignored during single block (SBL)"],
  ["chan-38-0","chan","DBX",38,0,"NC->PLC","stroke initiation active"],
  ["chan-38-1","chan","DBX",38,1,"NC->PLC","manual stroke initiation: Acknowledgment"],
  ["chan-39-5","chan","DBX",39,5,"NC->PLC","Contour handwheel: handwheel direction of rotation inversion active"],
  ["chan-40-0","chan","DBX",40,0,"NC->PLC","geometry axis 1: handwheel active"],
  ["chan-40-1","chan","DBX",40,1,"NC->PLC","geometry axis 1: handwheel active"],
  ["chan-40-2","chan","DBX",40,2,"NC->PLC","geometry axis 1: handwheel active"],
  ["chan-40-4","chan","DBX",40,4,"NC->PLC","geometry axis 1: traversing request \"Plus\" / \"Minus\""],
  ["chan-40-5","chan","DBX",40,5,"NC->PLC","geometry axis 1: traversing request \"Plus\" / \"Minus\""],
  ["chan-40-6","chan","DBX",40,6,"NC->PLC","geometry axis 1: traversing command \"Plus\" / \"Minus\""],
  ["chan-40-7","chan","DBX",40,7,"NC->PLC","geometry axis 1: traversing command \"Plus\" / \"Minus\""],
  ["chan-41-0","chan","DBX",41,0,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-41-1","chan","DBX",41,1,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-41-2","chan","DBX",41,2,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-41-3","chan","DBX",41,3,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-41-4","chan","DBX",41,4,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-41-5","chan","DBX",41,5,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-41-6","chan","DBX",41,6,"NC->PLC","geometry axis 1: active machine function"],
  ["chan-43-0","chan","DBX",43,0,"NC->PLC","geometry axis 1: handwheel direction of rotation inversion active"],
  ["chan-46-0","chan","DBX",46,0,null,"geometry axis 2: handwheel active"],
  ["chan-46-1","chan","DBX",46,1,null,"geometry axis 2: handwheel active"],
  ["chan-46-2","chan","DBX",46,2,null,"geometry axis 2: handwheel active"],
  ["chan-46-4","chan","DBX",46,4,null,"geometry axis 2: traversing request \"Plus\" / \"Minus\""],
  ["chan-46-5","chan","DBX",46,5,null,"geometry axis 2: traversing request \"Plus\" / \"Minus\""],
  ["chan-46-6","chan","DBX",46,6,null,"geometry axis 2: traversing command \"Plus\" / \"Minus\""],
  ["chan-46-7","chan","DBX",46,7,null,"geometry axis 2: traversing command \"Plus\" / \"Minus\""],
  ["chan-47-0","chan","DBX",47,0,null,"geometry axis 2: active machine function"],
  ["chan-47-1","chan","DBX",47,1,null,"geometry axis 2: active machine function"],
  ["chan-47-2","chan","DBX",47,2,null,"geometry axis 2: active machine function"],
  ["chan-47-3","chan","DBX",47,3,null,"geometry axis 2: active machine function"],
  ["chan-47-4","chan","DBX",47,4,null,"geometry axis 2: active machine function"],
  ["chan-47-5","chan","DBX",47,5,null,"geometry axis 2: active machine function"],
  ["chan-47-6","chan","DBX",47,6,null,"geometry axis 2: active machine function"],
  ["chan-49-0","chan","DBX",49,0,null,"geometry axis 2: handwheel direction of rotation inversion active"],
  ["chan-52-0","chan","DBX",52,0,null,"geometry axis 3: handwheel active"],
  ["chan-52-1","chan","DBX",52,1,null,"geometry axis 3: handwheel active"],
  ["chan-52-2","chan","DBX",52,2,null,"geometry axis 3: handwheel active"],
  ["chan-52-4","chan","DBX",52,4,null,"geometry axis 3: traversing request \"Plus\" / \"Minus\""],
  ["chan-52-5","chan","DBX",52,5,null,"geometry axis 3: traversing request \"Plus\" / \"Minus\""],
  ["chan-52-6","chan","DBX",52,6,null,"geometry axis 3: traversing command \"Plus\" / \"Minus\""],
  ["chan-52-7","chan","DBX",52,7,null,"geometry axis 3: traversing command \"Plus\" / \"Minus\""],
  ["chan-53-0","chan","DBX",53,0,null,"geometry axis 3: active machine function"],
  ["chan-53-1","chan","DBX",53,1,null,"geometry axis 3: active machine function"],
  ["chan-53-2","chan","DBX",53,2,null,"geometry axis 3: active machine function"],
  ["chan-53-3","chan","DBX",53,3,null,"geometry axis 3: active machine function"],
  ["chan-53-4","chan","DBX",53,4,null,"geometry axis 3: active machine function"],
  ["chan-53-5","chan","DBX",53,5,null,"geometry axis 3: active machine function"],
  ["chan-53-6","chan","DBX",53,6,null,"geometry axis 3: active machine function"],
  ["chan-55-0","chan","DBX",55,0,null,"geometry axis 3: handwheel direction of rotation inversion active"],
  ["chan-58-b","chan","DBB",58,null,null,"M-, S-, T-, D-, H-, F fct. change"],
  ["chan-59-0","chan","DBX",59,0,"NC->PLC","M fct. 1-5 not decoded"],
  ["chan-59-1","chan","DBX",59,1,"NC->PLC","M fct. 1-5 not decoded"],
  ["chan-59-2","chan","DBX",59,2,"NC->PLC","M fct. 1-5 not decoded"],
  ["chan-59-3","chan","DBX",59,3,"NC->PLC","M fct. 1-5 not decoded"],
  ["chan-59-4","chan","DBX",59,4,"NC->PLC","M fct. 1-5 not decoded"],
  ["chan-60-b","chan","DBB",60,null,null,"M-, S-, T-, D-, H-, F fct. Additional quick information (quick acknowledgment"],
  ["chan-68-b","chan","DBB",68,null,"NC->PLC","M function 1 - 5 and extended address M function 1 - 5"],
  ["chan-98-b","chan","DBB",98,null,"NC->PLC","S function 1 - 3 and extended address S function 1 - 3"],
  ["chan-118-b","chan","DBB",118,null,null,"T function 1"],
  ["chan-129-b","chan","DBB",129,null,"NC->PLC","D function 1"],
  ["chan-140-b","chan","DBB",140,null,"NC->PLC","H function 1 - 3 and extended address H function 1 - 3"],
  ["chan-158-b","chan","DBB",158,null,"NC->PLC","F function 1 - 6 and extended address F function 1 - 6"],
  ["chan-194-b","chan","DBB",194,null,null,"dynamic M functions: M0 - M99"],
  ["chan-208-b","chan","DBB",208,null,"NC->PLC","active G command of group 1 to 60"],
  ["chan-272-0","chan","DBX",272,0,"NC->PLC","machine-related protection zone 1 - 10 preactivated"],
  ["chan-274-0","chan","DBX",274,0,"NC->PLC","channel-specific protection zone 1 - 10 preactivated"],
  ["chan-276-0","chan","DBX",276,0,"NC->PLC","machine-related protection zone 1 - 10 violated"],
  ["chan-278-0","chan","DBX",278,0,"NC->PLC","channel-specific protection zone 1 - 10 violated"],
  ["chan-317-1","chan","DBB",317,1,null,"workpiece setpoint reached"],
  ["chan-317-6","chan","DBX",317,6,"NC->PLC","PTP traversing active"],
  ["chan-317-7","chan","DBX",317,7,"NC->PLC","TOOLMAN: Tool missing"],
  ["chan-318-0","chan","DBX",318,0,"NC->PLC","ASUB is stopped"],
  ["chan-318-1","chan","DBX",318,1,"NC->PLC","block search via program test is active (SERUPRO)"],
  ["chan-318-2","chan","DBX",318,2,"NC->PLC","online tool length compensation (TOFF) active"],
  ["chan-318-3","chan","DBX",318,3,"NC->PLC","online tool length compensation (TOFF): Compensation motion active"],
  ["chan-318-5","chan","DBX",318,5,"NC->PLC","associated M0 / M1 active"],
  ["chan-319-0","chan","DBX",319,0,"NC->PLC","REPOS mode change acknowledgment"],
  ["chan-319-1","chan","DBX",319,1,"NC->PLC","active REPOS mode"],
  ["chan-319-2","chan","DBX",319,2,"NC->PLC","active REPOS mode"],
  ["chan-319-3","chan","DBX",319,3,"NC->PLC","active REPOS mode"],
  ["chan-319-5","chan","DBX",319,5,"NC->PLC","REPOS delay"],
  ["chan-320-0","chan","DBX",320,0,"PLC->NC","orientation axis 1: activate handwheel"],
  ["chan-320-1","chan","DBX",320,1,"PLC->NC","orientation axis 1: activate handwheel"],
  ["chan-320-2","chan","DBX",320,2,"PLC->NC","orientation axis 1: activate handwheel"],
  ["chan-320-4","chan","DBX",320,4,"PLC->NC","orientation axis 1: traversing key lock"],
  ["chan-320-5","chan","DBX",320,5,"PLC->NC","orientation axis 1: rapid traverse override"],
  ["chan-320-6","chan","DBX",320,6,"PLC->NC","Orientierungsachse 1: traversing keys \"Plus\" / \"Minus\""],
  ["chan-320-7","chan","DBX",320,7,"PLC->NC","Orientierungsachse 1: traversing keys \"Plus\" / \"Minus\""],
  ["chan-321-0","chan","DBX",321,0,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-321-1","chan","DBX",321,1,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-321-2","chan","DBX",321,2,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-321-3","chan","DBX",321,3,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-321-4","chan","DBX",321,4,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-321-5","chan","DBX",321,5,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-321-6","chan","DBX",321,6,"PLC->NC","orientation axis 1: machine function request"],
  ["chan-323-0","chan","DBX",323,0,"PLC->NC","orientation axis 1: invert handwheel direction of rotation"],
  ["chan-324-0","chan","DBX",324,0,null,"orientation axis 2: activate handwheel"],
  ["chan-324-1","chan","DBX",324,1,null,"orientation axis 2: activate handwheel"],
  ["chan-324-2","chan","DBX",324,2,null,"orientation axis 2: activate handwheel"],
  ["chan-324-4","chan","DBX",324,4,null,"orientation axis 2: traversing key lock"],
  ["chan-324-5","chan","DBX",324,5,null,"orientation axis 2: rapid traverse override"],
  ["chan-324-6","chan","DBX",324,6,null,"orientation axis 2: traversing keys \"Plus\" / \"Minus\""],
  ["chan-324-7","chan","DBX",324,7,null,"orientation axis 2: traversing keys \"Plus\" / \"Minus\""],
  ["chan-325-0","chan","DBX",325,0,null,"orientation axis 2: machine function request"],
  ["chan-325-1","chan","DBX",325,1,null,"orientation axis 2: machine function request"],
  ["chan-325-2","chan","DBX",325,2,null,"orientation axis 2: machine function request"],
  ["chan-325-3","chan","DBX",325,3,null,"orientation axis 2: machine function request"],
  ["chan-325-4","chan","DBX",325,4,null,"orientation axis 2: machine function request"],
  ["chan-325-5","chan","DBX",325,5,null,"orientation axis 2: machine function request"],
  ["chan-325-6","chan","DBX",325,6,null,"orientation axis 2: machine function request"],
  ["chan-327-0","chan","DBX",327,0,null,"orientation axis 2: invert handwheel direction of rotation"],
  ["chan-328-0","chan","DBX",328,0,null,"orientation axis 3: activate handwheel"],
  ["chan-328-1","chan","DBX",328,1,null,"orientation axis 3: activate handwheel"],
  ["chan-328-2","chan","DBX",328,2,null,"orientation axis 3: activate handwheel"],
  ["chan-328-4","chan","DBX",328,4,null,"orientation axis 3: traversing key lock"],
  ["chan-328-5","chan","DBX",328,5,null,"orientation axis 3: rapid traverse override"],
  ["chan-328-6","chan","DBX",328,6,null,"orientation axis 3: traversing keys \"Plus\" / \"Minus\""],
  ["chan-328-7","chan","DBX",328,7,null,"orientation axis 3: traversing keys \"Plus\" / \"Minus\""],
  ["chan-329-0","chan","DBX",329,0,null,"orientation axis 3: machine function request"],
  ["chan-329-1","chan","DBX",329,1,null,"orientation axis 3: machine function request"],
  ["chan-329-2","chan","DBX",329,2,null,"orientation axis 3: machine function request"],
  ["chan-329-3","chan","DBX",329,3,null,"orientation axis 3: machine function request"],
  ["chan-329-4","chan","DBX",329,4,null,"orientation axis 3: machine function request"],
  ["chan-329-5","chan","DBX",329,5,null,"orientation axis 3: machine function request"],
  ["chan-329-6","chan","DBX",329,6,null,"orientation axis 3: machine function request"],
  ["chan-331-0","chan","DBX",331,0,null,"orientation axis 3: invert handwheel direction of rotation"],
  ["chan-332-0","chan","DBX",332,0,"NC->PLC","orientation axis 1: handwheel active"],
  ["chan-332-1","chan","DBX",332,1,"NC->PLC","orientation axis 1: handwheel active"],
  ["chan-332-2","chan","DBX",332,2,"NC->PLC","orientation axis 1: handwheel active"],
  ["chan-332-4","chan","DBX",332,4,"NC->PLC","orientation axis 1: traversing request \"Plus\" / \"Minus\""],
  ["chan-332-5","chan","DBX",332,5,"NC->PLC","orientation axis 1: traversing request \"Plus\" / \"Minus\""],
  ["chan-332-6","chan","DBX",332,6,"NC->PLC","orientation axis 1: traversing command \"Plus\" / \"Minus\" DB21,"],
  ["chan-332-7","chan","DBX",332,7,"NC->PLC","orientation axis 1: traversing command \"Plus\" / \"Minus\" DB21,"],
  ["chan-333-0","chan","DBX",333,0,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-333-1","chan","DBX",333,1,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-333-2","chan","DBX",333,2,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-333-3","chan","DBX",333,3,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-333-4","chan","DBX",333,4,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-333-5","chan","DBX",333,5,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-333-6","chan","DBX",333,6,"NC->PLC","orientation axis 1: active machine function"],
  ["chan-336-0","chan","DBX",336,0,null,"orientation axis 2: handwheel active"],
  ["chan-336-1","chan","DBX",336,1,null,"orientation axis 2: handwheel active"],
  ["chan-336-2","chan","DBX",336,2,null,"orientation axis 2: handwheel active"],
  ["chan-336-4","chan","DBX",336,4,null,"orientation axis 2: traversing request \"Plus\" / \"Minus\""],
  ["chan-336-5","chan","DBX",336,5,null,"orientation axis 2: traversing request \"Plus\" / \"Minus\""],
  ["chan-336-6","chan","DBX",336,6,null,"orientation axis 2: traversing command \"Plus\" / \"Minus\" DB21,"],
  ["chan-336-7","chan","DBX",336,7,null,"orientation axis 2: traversing command \"Plus\" / \"Minus\" DB21,"],
  ["chan-337-0","chan","DBX",337,0,null,"orientation axis 2: active machine function"],
  ["chan-337-1","chan","DBX",337,1,null,"orientation axis 2: active machine function"],
  ["chan-337-2","chan","DBX",337,2,null,"orientation axis 2: active machine function"],
  ["chan-337-3","chan","DBX",337,3,null,"orientation axis 2: active machine function"],
  ["chan-337-4","chan","DBX",337,4,null,"orientation axis 2: active machine function"],
  ["chan-337-5","chan","DBX",337,5,null,"orientation axis 2: active machine function"],
  ["chan-337-6","chan","DBX",337,6,null,"orientation axis 2: active machine function"],
  ["chan-340-0","chan","DBX",340,0,null,"orientation axis 3: handwheel active"],
  ["chan-340-1","chan","DBX",340,1,null,"orientation axis 3: handwheel active"],
  ["chan-340-2","chan","DBX",340,2,null,"orientation axis 3: handwheel active"],
  ["chan-340-4","chan","DBX",340,4,null,"orientation axis 3: traversing request \"Plus\" / \"Minus\""],
  ["chan-340-5","chan","DBX",340,5,null,"orientation axis 3: traversing request \"Plus\" / \"Minus\""],
  ["chan-340-6","chan","DBX",340,6,null,"orientation axis 3: traversing command \"Plus\" / \"Minus\" DB21,"],
  ["chan-340-7","chan","DBX",340,7,null,"orientation axis 3: traversing command \"Plus\" / \"Minus\" DB21,"],
  ["chan-341-0","chan","DBX",341,0,null,"orientation axis 3: active machine function"],
  ["chan-341-1","chan","DBX",341,1,null,"orientation axis 3: active machine function"],
  ["chan-341-2","chan","DBX",341,2,null,"orientation axis 3: active machine function"],
  ["chan-341-3","chan","DBX",341,3,null,"orientation axis 3: active machine function"],
  ["chan-341-4","chan","DBX",341,4,null,"orientation axis 3: active machine function"],
  ["chan-341-5","chan","DBX",341,5,null,"orientation axis 3: active machine function"],
  ["chan-341-6","chan","DBX",341,6,null,"orientation axis 3: active machine function"],
  ["chan-344-0","chan","DBX",344,0,"PLC->NC","TM: tool prewarning limit reached"],
  ["chan-344-1","chan","DBX",344,1,"PLC->NC","TM: Tool limit value reached"],
  ["chan-344-2","chan","DBX",344,2,"PLC->NC","TM: Transition to new replacement tool"],
  ["chan-344-3","chan","DBX",344,3,"PLC->NC","TM: Last replacement tool of the tool group"],
  ["chan-376-b","chan","DBB",376,null,"NC->PLC","PROG_EVENT trigger event"],
  ["chan-377-0","chan","DBX",377,0,"NC->PLC","collision avoidance: stop"],
  ["chan-377-4","chan","DBX",377,4,"NC->PLC","JOG retract active"],
  ["chan-377-5","chan","DBX",377,5,"NC->PLC","JOG retract retraction data available"],
  ["chan-377-6","chan","DBX",377,6,"NC->PLC","JOG circular travel active"],
  ["chan-378-0","chan","DBX",378,0,"NC->PLC","ASUB active"],
  ["chan-378-1","chan","DBX",378,1,"NC->PLC","stopped ASUB active"],
  ["chan-384-0","chan","DBX",384,0,"PLC->NC","enable GOTOS"],
  ["chan-392-b","chan","DBB",392,null,"PLC->NC","selection: Coordinate system for Cartesian manual traversing and handwheel override in automatic mode in the tool direction (DRF)"],
  ["axis-0-b","axis","DBB",0,null,"PLC->NC","feedrate override, axis-specific"],
  ["axis-1-0","axis","DBX",1,0,"PLC->NC","drive test travel enable"],
  ["axis-1-1","axis","DBX",1,1,"PLC->NC","acknowledge fixed stop reached"],
  ["axis-1-2","axis","DBX",1,2,"PLC->NC","fixed stop sensor"],
  ["axis-1-3","axis","DBX",1,3,"PLC->NC","axis/spindle disable"],
  ["axis-1-4","axis","DBX",1,4,"PLC->NC","follow-up mode"],
  ["axis-1-5","axis","DBX",1,5,"PLC->NC","position measuring system 1 (PMS1) / position measuring system 2 (PMS2)"],
  ["axis-1-6","axis","DBX",1,6,"PLC->NC","position measuring system 1 (PMS1) / position measuring system 2 (PMS2)"],
  ["axis-1-7","axis","DBX",1,7,"PLC->NC","feedrate/speed override active"],
  ["axis-2-0","axis","DBX",2,0,"PLC->NC","software cams: activation"],
  ["axis-2-1","axis","DBX",2,1,"PLC->NC","controller enable"],
  ["axis-2-2","axis","DBX",2,2,"PLC->NC","spindle reset/delete distance to go"],
  ["axis-2-3","axis","DBX",2,3,"PLC->NC","clamping in progress"],
  ["axis-2-4","axis","DBX",2,4,"PLC->NC","reference point value 1 - 4"],
  ["axis-2-5","axis","DBX",2,5,"PLC->NC","reference point value 1 - 4"],
  ["axis-2-6","axis","DBX",2,6,"PLC->NC","reference point value 1 - 4"],
  ["axis-2-7","axis","DBX",2,7,"PLC->NC","reference point value 1 - 4"],
  ["axis-3-0","axis","DBX",3,0,"PLC->NC","accept external work offset"],
  ["axis-3-1","axis","DBX",3,1,"PLC->NC","enable travel to fixed stop"],
  ["axis-3-2","axis","DBX",3,2,null,"activate fixed feedrate 1 - 4, machine axes"],
  ["axis-3-3","axis","DBX",3,3,null,"activate fixed feedrate 1 - 4, machine axes"],
  ["axis-3-4","axis","DBX",3,4,null,"activate fixed feedrate 1 - 4, machine axes"],
  ["axis-3-5","axis","DBX",3,5,null,"activate fixed feedrate 1 - 4, machine axes"],
  ["axis-3-6","axis","DBX",3,6,"PLC->NC","velocity/spindle speed limiting"],
  ["axis-4-0","axis","DBX",4,0,"PLC->NC","activate handwheel"],
  ["axis-4-1","axis","DBX",4,1,"PLC->NC","activate handwheel"],
  ["axis-4-2","axis","DBX",4,2,"PLC->NC","activate handwheel"],
  ["axis-4-3","axis","DBX",4,3,"PLC->NC","feedrate/spindle stop, axis-specific"],
  ["axis-4-4","axis","DBX",4,4,"PLC->NC","traversing key disable"],
  ["axis-4-5","axis","DBX",4,5,"PLC->NC","rapid traverse override"],
  ["axis-4-6","axis","DBX",4,6,"PLC->NC","\"Plus\" / \"Minus\" traversing keys"],
  ["axis-4-7","axis","DBX",4,7,"PLC->NC","\"Plus\" / \"Minus\" traversing keys"],
  ["axis-5-0","axis","DBX",5,0,"PLC->NC","machine function request"],
  ["axis-5-1","axis","DBX",5,1,"PLC->NC","machine function request"],
  ["axis-5-2","axis","DBX",5,2,"PLC->NC","machine function request"],
  ["axis-5-3","axis","DBX",5,3,"PLC->NC","machine function request"],
  ["axis-5-4","axis","DBX",5,4,"PLC->NC","machine function request"],
  ["axis-5-5","axis","DBX",5,5,"PLC->NC","machine function request"],
  ["axis-5-6","axis","DBX",5,6,"PLC->NC","machine function request"],
  ["axis-7-0","axis","DBX",7,0,"PLC->NC","invert handwheel direction of rotation"],
  ["axis-8-b","axis","DBB",8,null,"PLC->NC","request axis/spindle replacement"],
  ["axis-9-0","axis","DBX",9,0,"PLC->NC","2 select: position controller parameter set"],
  ["axis-9-3","axis","DBX",9,3,"PLC->NC","parameter set definitions disabled by NC"],
  ["axis-10-0","axis","DBX",10,0,"PLC->NC","REPOS delay"],
  ["axis-12-0","axis","DBX",12,0,"PLC->NC","hardware limit switch minus"],
  ["axis-12-1","axis","DBX",12,1,"PLC->NC","hardware limit switch plus"],
  ["axis-12-2","axis","DBX",12,2,"PLC->NC","second software limit switch minus"],
  ["axis-12-3","axis","DBX",12,3,"PLC->NC","second software limit switch plus"],
  ["axis-12-4","axis","DBX",12,4,"PLC->NC","modulo rotary axis: activate traversing range limits"],
  ["axis-12-7","axis","DBX",12,7,"PLC->NC","reference point approach deceleration"],
  ["axis-13-0","axis","DBX",13,0,"PLC->NC","JOG approach fixed point"],
  ["axis-13-1","axis","DBX",13,1,"PLC->NC","JOG approach fixed point"],
  ["axis-13-2","axis","DBX",13,2,"PLC->NC","JOG approach fixed point"],
  ["axis-13-3","axis","DBX",13,3,"PLC->NC","JOG travel to position"],
  ["axis-14-0","axis","DBX",14,0,"PLC->NC","suppress program test"],
  ["axis-14-1","axis","DBX",14,1,"PLC->NC","activate program test"],
  ["axis-16-0","axis","DBX",16,0,"PLC->NC","actual gear stage"],
  ["axis-16-1","axis","DBX",16,1,"PLC->NC","actual gear stage"],
  ["axis-16-2","axis","DBX",16,2,"PLC->NC","actual gear stage"],
  ["axis-16-3","axis","DBX",16,3,"PLC->NC","gear stage has been changed"],
  ["axis-16-4","axis","DBX",16,4,"PLC->NC","resynchronize spindle, measuring system 1"],
  ["axis-16-5","axis","DBX",16,5,"PLC->NC","resynchronize spindle, measuring system 2"],
  ["axis-16-7","axis","DBX",16,7,"PLC->NC","delete S value"],
  ["axis-17-4","axis","DBX",17,4,"PLC->NC","resynchronizing the spindle before positioning, measuring system 1"],
  ["axis-17-5","axis","DBX",17,5,"PLC->NC","resynchronizing the spindle before positioning, measuring system 2"],
  ["axis-17-6","axis","DBX",17,6,"PLC->NC","invert M3 / M4"],
  ["axis-18-4","axis","DBX",18,4,"PLC->NC","oscillation controlled by the PLC"],
  ["axis-18-5","axis","DBX",18,5,"PLC->NC","oscillation enable"],
  ["axis-18-6","axis","DBX",18,6,"PLC->NC","oscillation: counterclockwise direction of rotation"],
  ["axis-18-7","axis","DBX",18,7,"PLC->NC","oscillation: clockwise direction of rotation"],
  ["axis-19-b","axis","DBB",19,null,"PLC->NC","speed override, spindle-specific"],
  ["axis-20-1","axis","DBX",20,1,"PLC->NC","ramp-function generator disable"],
  ["axis-21-0","axis","DBX",21,0,"PLC->NC","motor/drive data set: selection"],
  ["axis-21-1","axis","DBX",21,1,"PLC->NC","motor/drive data set: selection"],
  ["axis-21-2","axis","DBX",21,2,"PLC->NC","motor/drive data set: selection"],
  ["axis-21-3","axis","DBX",21,3,"PLC->NC","motor/drive data set: selection"],
  ["axis-21-4","axis","DBX",21,4,"PLC->NC","motor/drive data set: selection"],
  ["axis-21-5","axis","DBX",21,5,"PLC->NC","motor has been selected"],
  ["axis-21-6","axis","DBX",21,6,"PLC->NC","integrator disable, speed controller"],
  ["axis-21-7","axis","DBX",21,7,"PLC->NC","pulse enable"],
  ["axis-22-0","axis","DBB",22,0,null,"SI: SBH/SG deselection"],
  ["axis-22-1","axis","DBB",22,1,null,"SI: SBH deselection"],
  ["axis-22-3","axis","DBB",22,3,null,"SI: SG selection"],
  ["axis-22-4","axis","DBB",22,4,null,"SI: SG selection"],
  ["axis-23-0","axis","DBB",23,0,null,"gear ratio selection"],
  ["axis-23-1","axis","DBB",23,1,null,"gear ratio selection"],
  ["axis-23-2","axis","DBB",23,2,null,"gear ratio selection"],
  ["axis-23-4","axis","DBB",23,4,null,"SI: SE selection"],
  ["axis-24-2","axis","DBX",24,2,"PLC->NC","MCS coupling: deactivate or do not permit"],
  ["axis-24-3","axis","DBX",24,3,"PLC->NC","MCS coupling: activate collision protection"],
  ["axis-24-4","axis","DBX",24,4,"PLC->NC","master-slave: activate torque compensatory controller"],
  ["axis-24-5","axis","DBX",24,5,"PLC->NC","setpoint switchover: request drive control"],
  ["axis-24-7","axis","DBX",24,7,"PLC->NC","master-slave: activate coupling"],
  ["axis-26-4","axis","DBX",26,4,"PLC->NC","enable following axis override"],
  ["axis-28-0","axis","DBX",28,0,"PLC->NC","oscillation reversal from external"],
  ["axis-28-1","axis","DBX",28,1,"PLC->NC","PLC-controlled axis: Reset"],
  ["axis-28-2","axis","DBX",28,2,"PLC->NC","PLC-controlled axis: Resume"],
  ["axis-28-3","axis","DBX",28,3,"PLC->NC","set reversal point"],
  ["axis-28-4","axis","DBX",28,4,"PLC->NC","change reversal point"],
  ["axis-28-5","axis","DBX",28,5,"PLC->NC","PLC-controlled axis: Stop at the next reversal point"],
  ["axis-28-6","axis","DBX",28,6,"PLC->NC","PLC-controlled axis: Stop along braking ramp"],
  ["axis-28-7","axis","DBX",28,7,"PLC->NC","request, PLC-controlled axis"],
  ["axis-31-5","axis","DBX",31,5,"PLC->NC","disable synchronization"],
  ["axis-34-0","axis","DBX",34,0,"PLC->NC","setpoint limitation"],
  ["axis-34-1","axis","DBX",34,1,"PLC->NC","setpoint limitation"],
  ["axis-60-0","axis","DBX",60,0,"NC->PLC","spindle / rotary axis"],
  ["axis-60-1","axis","DBX",60,1,"NC->PLC","NCU link axis active"],
  ["axis-60-2","axis","DBX",60,2,"NC->PLC","encoder limit frequency exceeded 1"],
  ["axis-60-3","axis","DBX",60,3,"NC->PLC","encoder frequency limit exceeded, measuring system 2"],
  ["axis-60-4","axis","DBX",60,4,"NC->PLC","referenced/synchronized 1"],
  ["axis-60-5","axis","DBX",60,5,"NC->PLC","referenced/synchronized 2"],
  ["axis-60-6","axis","DBX",60,6,"NC->PLC","position reached with exact stop coarse"],
  ["axis-60-7","axis","DBX",60,7,"NC->PLC","position reached with exact stop fine"],
  ["axis-61-0","axis","DBX",61,0,"NC->PLC","drive test travel request"],
  ["axis-61-1","axis","DBX",61,1,"NC->PLC","axis-specific alarm"],
  ["axis-61-2","axis","DBX",61,2,"NC->PLC","axis ready"],
  ["axis-61-3","axis","DBX",61,3,"NC->PLC","follow-up active"],
  ["axis-61-4","axis","DBX",61,4,"NC->PLC","axis/spindle stationary (n < nmin)"],
  ["axis-61-5","axis","DBX",61,5,"NC->PLC","position controller active"],
  ["axis-61-6","axis","DBX",61,6,"NC->PLC","speed controller active"],
  ["axis-61-7","axis","DBX",61,7,"NC->PLC","current controller active"],
  ["axis-62-0","axis","DBX",62,0,"NC->PLC","software cams active"],
  ["axis-62-1","axis","DBX",62,1,"NC->PLC","handwheel override active"],
  ["axis-62-2","axis","DBX",62,2,"NC->PLC","revolutional feedrate active"],
  ["axis-62-3","axis","DBX",62,3,"NC->PLC","measurement active"],
  ["axis-62-4","axis","DBX",62,4,"NC->PLC","activate travel to fixed stop"],
  ["axis-62-5","axis","DBX",62,5,"NC->PLC","fixed stop reached"],
  ["axis-62-7","axis","DBX",62,7,"NC->PLC","axis container rotation active"],
  ["axis-63-0","axis","DBX",63,0,"NC->PLC","reset executed"],
  ["axis-63-1","axis","DBX",63,1,"NC->PLC","PLC-controlled axis"],
  ["axis-63-2","axis","DBX",63,2,"NC->PLC","axis stop active"],
  ["axis-64-0","axis","DBX",64,0,"NC->PLC","handwheel active"],
  ["axis-64-1","axis","DBX",64,1,"NC->PLC","handwheel active"],
  ["axis-64-2","axis","DBX",64,2,"NC->PLC","handwheel active"],
  ["axis-64-4","axis","DBX",64,4,"NC->PLC","\"Plus\" / \"Minus\" traversing request"],
  ["axis-64-5","axis","DBX",64,5,"NC->PLC","\"Plus\" / \"Minus\" traversing request"],
  ["axis-64-6","axis","DBX",64,6,"NC->PLC","\"Plus\" / \"Minus\" traversing command"],
  ["axis-64-7","axis","DBX",64,7,"NC->PLC","\"Plus\" / \"Minus\" traversing command"],
  ["axis-65-0","axis","DBX",65,0,"NC->PLC","active machine function"],
  ["axis-65-1","axis","DBX",65,1,"NC->PLC","active machine function"],
  ["axis-65-2","axis","DBX",65,2,"NC->PLC","active machine function"],
  ["axis-65-3","axis","DBX",65,3,"NC->PLC","active machine function"],
  ["axis-65-4","axis","DBX",65,4,"NC->PLC","active machine function"],
  ["axis-65-5","axis","DBX",65,5,"NC->PLC","active machine function"],
  ["axis-65-6","axis","DBX",65,6,"NC->PLC","active machine function"],
  ["axis-66-0","axis","DBX",66,0,"NC->PLC","MCS coupling: collision protection active"],
  ["axis-67-0","axis","DBX",67,0,"NC->PLC","handwheel direction of rotation inversion active"],
  ["axis-68-b","axis","DBB",68,null,"PLC->NC","status axis/spindle replacement"],
  ["axis-69-0","axis","DBX",69,0,"NC->PLC","active position controller parameter set"],
  ["axis-69-1","axis","DBX",69,1,"NC->PLC","active position controller parameter set"],
  ["axis-69-2","axis","DBX",69,2,"NC->PLC","active position controller parameter set"],
  ["axis-70-0","axis","DBX",70,0,"NC->PLC","REPOS offset"],
  ["axis-70-1","axis","DBX",70,1,"NC->PLC","REPOS offset valid"],
  ["axis-70-2","axis","DBX",70,2,"NC->PLC","REPOS delay acknowledgment"],
  ["axis-71-4","axis","DBX",71,4,"NC->PLC","position restored measuring system 1"],
  ["axis-71-5","axis","DBX",71,5,"NC->PLC","position restored, measuring system 2"],
  ["axis-72-0","axis","DBX",72,0,"NC->PLC","REPOS delay"],
  ["axis-74-4","axis","DBX",74,4,"NC->PLC","modulo rotary axis: traversing range limits active"],
  ["axis-75-0","axis","DBX",75,0,"NC->PLC","JOG approach fixed point active"],
  ["axis-75-1","axis","DBX",75,1,"NC->PLC","JOG approach fixed point active"],
  ["axis-75-2","axis","DBX",75,2,"NC->PLC","JOG approach fixed point active"],
  ["axis-75-3","axis","DBX",75,3,"NC->PLC","JOG approach fixed point reached"],
  ["axis-75-4","axis","DBX",75,4,"NC->PLC","JOG approach fixed point reached"],
  ["axis-75-5","axis","DBX",75,5,"NC->PLC","JOG approach fixed point reached"],
  ["axis-75-6","axis","DBX",75,6,"NC->PLC","JOG travel to position active"],
  ["axis-75-7","axis","DBX",75,7,"NC->PLC","JOG position reached"],
  ["axis-76-0","axis","DBX",76,0,"NC->PLC","lubrication pulse"],
  ["axis-76-4","axis","DBX",76,4,"NC->PLC","path axis"],
  ["axis-76-5","axis","DBX",76,5,"NC->PLC","positioning axis"],
  ["axis-76-6","axis","DBX",76,6,"NC->PLC","indexing axis in position"],
  ["axis-77-0","axis","DBX",77,0,"NC->PLC","collision avoidance: Velocity reduction"],
  ["axis-78-b","axis","DBD",78,null,"NC->PLC","feedrate, positioning axis"],
  ["axis-82-0","axis","DBX",82,0,"NC->PLC","set gear stage"],
  ["axis-82-1","axis","DBX",82,1,"NC->PLC","set gear stage"],
  ["axis-82-2","axis","DBX",82,2,"NC->PLC","set gear stage"],
  ["axis-82-3","axis","DBX",82,3,null,"change over gear stage"],
  ["axis-83-0","axis","DBX",83,0,"NC->PLC","speed limit exceeded"],
  ["axis-83-1","axis","DBX",83,1,"NC->PLC","speed setpoint limited"],
  ["axis-83-2","axis","DBX",83,2,"NC->PLC","speed setpoint increased"],
  ["axis-83-3","axis","DBX",83,3,"NC->PLC","geometry monitoring"],
  ["axis-83-5","axis","DBX",83,5,"NC->PLC","spindle in setpoint range"],
  ["axis-83-6","axis","DBX",83,6,"NC->PLC","speed monitoring"],
  ["axis-83-7","axis","DBX",83,7,"NC->PLC","clockwise actual direction of rotation"],
  ["axis-84-1","axis","DBX",84,1,"NC->PLC","grinding wheel peripheral speed active"],
  ["axis-84-3","axis","DBX",84,3,"NC->PLC","tapping without compensating check active"],
  ["axis-84-4","axis","DBX",84,4,"NC->PLC","active spindle operating mode: Synchronous operation"],
  ["axis-84-5","axis","DBX",84,5,"NC->PLC","active spindle mode: positioning mode"],
  ["axis-84-6","axis","DBX",84,6,"NC->PLC","active spindle mode: oscillating mode"],
  ["axis-84-7","axis","DBX",84,7,"NC->PLC","active spindle mode: control mode"],
  ["axis-85-5","axis","DBX",85,5,"NC->PLC","spindle in position"],
  ["axis-86-b","axis","DBW",86,null,"NC->PLC","M function for spindle"],
  ["axis-88-b","axis","DBD",88,null,"NC->PLC","S function for spindle"],
  ["axis-92-1","axis","DBX",92,1,"NC->PLC","ramp-function generator disable active"],
  ["axis-92-4","axis","DBX",92,4,"NC->PLC","drive-autonomous motion active"],
  ["axis-93-0","axis","DBX",93,0,"NC->PLC","motor/drive data set: display"],
  ["axis-93-1","axis","DBX",93,1,"NC->PLC","motor/drive data set: display"],
  ["axis-93-2","axis","DBX",93,2,"NC->PLC","motor/drive data set: display"],
  ["axis-93-3","axis","DBX",93,3,"NC->PLC","motor/drive data set: display"],
  ["axis-93-4","axis","DBX",93,4,"NC->PLC","motor/drive data set: display"],
  ["axis-93-5","axis","DBX",93,5,"NC->PLC","drive ready"],
  ["axis-93-6","axis","DBX",93,6,"NC->PLC","integrator speed controller disabled"],
  ["axis-93-7","axis","DBX",93,7,"NC->PLC","pulses enabled"],
  ["axis-94-0","axis","DBX",94,0,"NC->PLC","motor temperature prewarning"],
  ["axis-94-1","axis","DBX",94,1,"NC->PLC","heat sink temperature prewarning"],
  ["axis-94-2","axis","DBX",94,2,"NC->PLC","run-up completed"],
  ["axis-94-3","axis","DBX",94,3,"NC->PLC","|Md| < Mdx"],
  ["axis-94-4","axis","DBX",94,4,"NC->PLC","|nact| < nmin"],
  ["axis-94-5","axis","DBX",94,5,"NC->PLC","|nact| < nx"],
  ["axis-94-6","axis","DBX",94,6,"NC->PLC","nact = nset"],
  ["axis-94-7","axis","DBX",94,7,"NC->PLC","variable signaling function"],
  ["axis-95-1","axis","DBX",95,1,"NC->PLC","ESR: DC link undervoltage"],
  ["axis-95-2","axis","DBX",95,2,"NC->PLC","ESR: Response initiated or generator operation active"],
  ["axis-95-3","axis","DBX",95,3,"NC->PLC","generator operation minimum speed fallen below"],
  ["axis-95-7","axis","DBX",95,7,"NC->PLC","alarm of alarm class C is active"],
  ["axis-96-2","axis","DBX",96,2,"NC->PLC","master-slave: fine differential speed"],
  ["axis-96-3","axis","DBX",96,3,"NC->PLC","master-slave: coarse speed difference"],
  ["axis-96-4","axis","DBX",96,4,"NC->PLC","master-slave: compensatory controller active"],
  ["axis-96-5","axis","DBX",96,5,"NC->PLC","setpoint switchover: drive control active"],
  ["axis-96-7","axis","DBX",96,7,"NC->PLC","master-slave: coupling active"],
  ["axis-97-0","axis","DBX",97,0,"NC->PLC","MCS coupling: slave axis"],
  ["axis-97-1","axis","DBX",97,1,"NC->PLC","MCS coupling: coupling active"],
  ["axis-97-2","axis","DBX",97,2,"NC->PLC","MCS coupling: mirroring active"],
  ["axis-97-3","axis","DBX",97,3,"NC->PLC","MCS coupling: offset change"],
  ["axis-98-0","axis","DBX",98,0,"NC->PLC","fine synchronous operation"],
  ["axis-98-1","axis","DBX",98,1,"NC->PLC","coarse synchronous operation"],
  ["axis-98-2","axis","DBX",98,2,"NC->PLC","actual value coupling"],
  ["axis-98-4","axis","DBX",98,4,"NC->PLC","overlaid movement"],
  ["axis-98-5","axis","DBX",98,5,"NC->PLC","speed alarm threshold reached"],
  ["axis-98-6","axis","DBX",98,6,"NC->PLC","acceleration alarm threshold reached"],
  ["axis-99-0","axis","DBX",99,0,"NC->PLC","leading spindle active"],
  ["axis-99-1","axis","DBX",99,1,"NC->PLC","following spindle active"],
  ["axis-99-3","axis","DBX",99,3,"NC->PLC","axis accelerates"],
  ["axis-100-2","axis","DBX",100,2,"NC->PLC","oscillation reversal from external active"],
  ["axis-100-3","axis","DBX",100,3,"NC->PLC","oscillation cannot be started"],
  ["axis-100-4","axis","DBX",100,4,"NC->PLC","error during oscillation"],
  ["axis-100-5","axis","DBX",100,5,"NC->PLC","sparking-out active"],
  ["axis-100-6","axis","DBX",100,6,"NC->PLC","oscillation active"],
  ["axis-100-7","axis","DBX",100,7,"NC->PLC","oscillation active"],
  ["axis-102-5","axis","DBX",102,5,"NC->PLC","position measuring system 1 activated"],
  ["axis-102-6","axis","DBX",102,6,"NC->PLC","position measuring system 2 activated"],
  ["axis-104-0","axis","DBX",104,0,null,"active infeed axes"],
  ["axis-128-0","axis","DBX",128,0,null,"suppress program test"],
  ["axis-128-1","axis","DBX",128,1,null,"activate program test"],
  ["axis-130-0","axis","DBX",130,0,"NC->PLC","motor/drive data set: formatting"],
  ["axis-130-1","axis","DBX",130,1,"NC->PLC","motor/drive data set: formatting"],
  ["axis-130-2","axis","DBX",130,2,"NC->PLC","motor/drive data set: formatting"],
  ["axis-130-3","axis","DBX",130,3,"NC->PLC","motor/drive data set: formatting"],
  ["axis-130-4","axis","DBX",130,4,"NC->PLC","motor/drive data set: formatting"],
  ["axis-132-0","axis","DBX",132,0,"NC->PLC","sensors available"],
  ["axis-132-1","axis","DBX",132,1,"NC->PLC","sensor S1 available (clamped state)"],
  ["axis-132-4","axis","DBX",132,4,"NC->PLC","sensor S4 available (piston end position)"],
  ["axis-132-5","axis","DBX",132,5,"NC->PLC","sensor S5 available (angular position of the motor shaft)"],
  ["axis-133-2","axis","DBX",133,2,"NC->PLC","state value is generated, speed limitation p5043 is active"],
  ["axis-134-b","axis","DBW",134,null,"NC->PLC","state of the clamping system (sensor S1)"],
  ["axis-136-b","axis","DBW",136,null,"NC->PLC","analog measured value: of the clamping system"],
  ["axis-138-4","axis","DBX",138,4,"NC->PLC","sensor S4, piston end position"],
  ["axis-138-5","axis","DBX",138,5,"NC->PLC","sensor S5 angular position of the motor shaft"],
];

export const SIGNALS = ROWS.map(([id, cls, type, byte, bit, dir, name]) => ({
    id, controls: SL_PL, area: CLASS[cls], type, byte, bit, name,
    dir: dir || null, confidence: "manual", source: SOURCE,
}));

function resolveLabel(entry, db) {
    const [lo, hi] = entry.area.db;
    if (lo === hi) return entry.area.label;
    return `${entry.area.label} ${db - entry.area.offset}`;
}
const addressOf = (e, db) =>
    `DB${db}.${e.type}${e.byte}${e.bit === null ? "" : "." + e.bit}`;
const decorate = (e, db) => ({ ...e, resolvedLabel: resolveLabel(e, db), address: addressOf(e, db) });

/** Find signals at an exact address on a control. [] for an honest miss. */
export function lookupSignal({ control, db, byte, bit }) {
    return SIGNALS.filter((s) => {
        if (!s.controls.includes(control)) return false;
        const [lo, hi] = s.area.db;
        return db >= lo && db <= hi && s.byte === byte && s.bit === (bit ?? null);
    }).map((s) => decorate(s, db));
}

/** Free-text search over signal names for a control. */
export function searchSignals({ control, query }) {
    const q = String(query || "").trim().toLowerCase();
    if (q === "") return [];
    return SIGNALS.filter(
        (s) => s.controls.includes(control) && s.name.toLowerCase().includes(q)
    )
        .slice(0, 200)
        .map((s) => decorate(s, s.area.db[0]));
}
